"""
Process ICT Signals
====================

Reads JSON signals generated by Python ICT Dashboard V2 and prepares them
for the Reasoning Module.
"""

import json
import logging
from pathlib import Path
from typing import Dict, List, Optional


logger = logging.getLogger('OpenClaw.skills.process_ict_signals')


class ProcessICTSignals:
    """Process ICT signals from JSON files."""
    
    def __init__(self, config: dict):
        self.config = config
        self.signals_dir = Path('signals_json')
    
    def read_signal_file(self, filepath: Path) -> Optional[Dict]:
        """Read a single signal file.
        
        Args:
            filepath: Path to JSON signal file
        
        Returns:
            Signal dictionary or None if invalid
        """
        try:
            with open(filepath, 'r') as f:
                signal = json.load(f)
            return signal
        except (json.JSONDecodeError, FileNotFoundError) as e:
            logger.error(f"Failed to read signal {filepath}: {e}")
            return None
    
    def read_all_signals(self) -> List[Dict]:
        """Read all signals from signals_json/ directory.
        
        Returns:
            List of signal dictionaries
        """
        signals = []
        if not self.signals_dir.exists():
            logger.warning(f"Signals directory not found: {self.signals_dir}")
            return signals
        
        for signal_file in self.signals_dir.glob('*.json'):
            signal = self.read_signal_file(signal_file)
            if signal:
                signals.append(signal)
                logger.info(f"Loaded signal: {signal.get('signal_id')}")
        
        return signals
    
    def validate_signal(self, signal: Dict) -> bool:
        """Validate signal has all required fields.
        
        Args:
            signal: Signal dictionary
        
        Returns:
            True if valid, False otherwise
        """
        required_fields = ['signal_id', 'type', 'direction', 'trading_pair', 'timeframe']
        for field in required_fields:
            if field not in signal:
                logger.error(f"Signal missing required field: {field}")
                return False
        return True


# Example usage
if __name__ == '__main__':
    config = {}
    processor = ProcessICTSignals(config)
    signals = processor.read_all_signals()
    print(f"Loaded {len(signals)} signals")
